[
    {
        "model" : "apps.Business",
        "pk" : 1,
        "fields" : {
            "qr_code" : "",
            "business_name" : "TJ-101",
            "barangay" : 1,
            "purok" : "Purok 1",
            "stall_no" : "alisdan ni",
            "gps_longitude" : "value",
            "gps_lattitude" : "value",
            "gps_altitude" : "value",
            "gps_accuracy" : "value",
            "business_owner_name" : "value",
            "business_owner_number" : "value",
            "business_representative" : "value",
            "owner_gender" : "value",
            "ownership_type" : "value",
            "is_business_permit" : "value",
            "business_permit_status" : "value",
            "is_notice" : "value",
            "notice_remarks" : "value",
            "business_status" : "value",
            "inactive_remarks" : "value",
            "inactive_reason" : "value",
            "fsic" : "value",
            "fsic_number" : "value",
            "application_status" : "value",
            "capitalization_amount" : "value",
            "gross_sale_amount" : 0,
            "total_employees" : 0,
            "total_male" : 0,
            "total_female" : 0,
            "location_status" : "rented or owned",
            "location_rental_amount" : 0,
            "lessor_name" : "value",
            "created_by" : 1,
            "team" : 1,
            "modified_by": 1
        }
    },
    {
        "model" : "apps.Business",
        "pk" : 2,
        "fields" : {
            "qr_code" : "",
            "business_name" : "TJ-101",
            "barangay" : 1,
            "purok" : "Purok 1",
            "stall_no" : "alisdan ni",
            "gps_longitude" : "value",
            "gps_lattitude" : "value",
            "gps_altitude" : "value",
            "gps_accuracy" : "value",
            "business_owner_name" : "value",
            "business_owner_number" : "value",
            "business_representative" : "value",
            "owner_gender" : "value",
            "ownership_type" : "value",
            "is_business_permit" : "value",
            "business_permit_status" : "value",
            "is_notice" : "value",
            "notice_remarks" : "value",
            "business_status" : "value",
            "inactive_remarks" : "value",
            "inactive_reason" : "value",
            "fsic" : "value",
            "fsic_number" : "value",
            "application_status" : "value",
            "capitalization_amount" : "value",
            "gross_sale_amount" : 0,
            "total_employees" : 0,
            "total_male" : 0,
            "total_female" : 0,
            "location_status" : "rented or owned",
            "location_rental_amount" : 0,
            "lessor_name" : "value",
            "created_by" : 1,
            "team" : 1,
            "modified_by": 1
        }
    },
    {
        "model" : "apps.Business",
        "pk" : 3,
        "fields" : {
            "qr_code" : "",
            "business_name" : "TJ-101",
            "barangay" : 1,
            "purok" : "Purok 1",
            "stall_no" : "alisdan ni",
            "gps_longitude" : "value",
            "gps_lattitude" : "value",
            "gps_altitude" : "value",
            "gps_accuracy" : "value",
            "business_owner_name" : "value",
            "business_owner_number" : "value",
            "business_representative" : "value",
            "owner_gender" : "value",
            "ownership_type" : "value",
            "is_business_permit" : "value",
            "business_permit_status" : "value",
            "is_notice" : "value",
            "notice_remarks" : "value",
            "business_status" : "value",
            "inactive_remarks" : "value",
            "inactive_reason" : "value",
            "fsic" : "value",
            "fsic_number" : "value",
            "application_status" : "value",
            "capitalization_amount" : "value",
            "gross_sale_amount" : 0,
            "total_employees" : 0,
            "total_male" : 0,
            "total_female" : 0,
            "location_status" : "rented or owned",
            "location_rental_amount" : 0,
            "lessor_name" : "value",
            "created_by" : 1,
            "team" : 1,
            "modified_by": 1
        }
    }

]
