# Generated by Django 3.2.4 on 2021-06-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ('business_name',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',)},
        ),
    ]
