# Generated by Django 3.2.4 on 2021-06-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210614_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_permit_picture',
            field=models.ImageField(upload_to='media/permit_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='collector_signature',
            field=models.ImageField(upload_to='media/collector_sig_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='goods_services_picture',
            field=models.ImageField(upload_to='media/goods_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='others1_picture',
            field=models.ImageField(upload_to='media/others_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='others2_picture',
            field=models.ImageField(upload_to='media/others_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner_picture',
            field=models.ImageField(upload_to='media/owner_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner_signature',
            field=models.ImageField(upload_to='media/owner_sig_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture1',
            field=models.ImageField(upload_to='media/add_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture2',
            field=models.ImageField(upload_to='media/add_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture3',
            field=models.ImageField(upload_to='media/add_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture4',
            field=models.ImageField(upload_to='media/add_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture5',
            field=models.ImageField(upload_to='media/add_pic/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture6',
            field=models.ImageField(upload_to='media/add_pic/'),
        ),
    ]
