# Generated by Django 3.2.4 on 2021-06-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20210617_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='barangay_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
