# Generated by Django 3.2.4 on 2021-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='owner_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, null=True),
        ),
    ]
