# Generated by Django 3.2.4 on 2021-06-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_business_owner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_business_permit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
