# Generated by Django 3.2.4 on 2021-06-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_business_is_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='fsic',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
