# Generated by Django 3.2.4 on 2021-06-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20210621_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='application_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
