# Generated by Django 3.2.4 on 2021-06-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_business_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
