# Generated by Django 3.2.4 on 2021-06-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('business', '0017_alter_business_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_business', to='team.team'),
        ),
    ]
