# Generated by Django 3.2.4 on 2021-06-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_business_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_permit_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='inactive_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
