# Generated by Django 3.2.4 on 2021-06-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20210623_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
