# Generated by Django 3.2.4 on 2021-06-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20210624_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='notice_date',
        ),
    ]
