# Generated by Django 3.2.4 on 2021-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_remove_business_notice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='gross_sale_amount',
        ),
        migrations.AddField(
            model_name='business',
            name='gross_sale_mount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
