# Generated by Django 3.2.4 on 2021-06-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20210627_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='gross_sale_mount',
            new_name='gross_sale_amount',
        ),
    ]
