# Generated by Django 3.2.4 on 2021-06-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_rename_gross_sale_mount_business_gross_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
