# Generated by Django 3.2.4 on 2021-06-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20210628_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='gross_sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
    ]
