# Generated by Django 3.2.4 on 2021-07-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
