# Generated by Django 3.2.4 on 2021-07-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_businesscategory_append_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='businesses',
            new_name='business',
        ),
    ]
