# Generated by Django 3.2.4 on 2021-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_rename_businesses_notification_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='append_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='append_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
