# Generated by Django 3.2.4 on 2021-07-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20210712_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessperiod',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-period_year']},
        ),
    ]
