# Generated by Django 3.2.4 on 2021-07-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_auto_20210712_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
