# Generated by Django 3.2.4 on 2021-07-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_period_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=50)),
                ('qrcode_image', models.ImageField(blank=True, upload_to='media/qrcodes')),
            ],
        ),
    ]
