# Generated by Django 3.2.4 on 2021-07-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='qr_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
