# Generated by Django 3.2.4 on 2021-07-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_alter_business_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='qr_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
