# Generated by Django 3.2.4 on 2021-07-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_alter_business_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='gps_accuracy',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_lattitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=7, null=True),
        ),
    ]
