# Generated by Django 3.2.4 on 2021-07-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_auto_20210716_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='gps_accuracy',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_lattitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10, null=True),
        ),
    ]
