# Generated by Django 3.2.4 on 2021-07-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_auto_20210717_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='gps_lattitude',
            new_name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='gps_all',
        ),
        migrations.RemoveField(
            model_name='business',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='business',
            name='payment_type',
        ),
    ]
