# Generated by Django 3.2.4 on 2021-07-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_auto_20210717_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='gps_altitude',
            new_name='gps_altitud',
        ),
    ]
