# Generated by Django 3.2.4 on 2021-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_rename_gps_altitude_business_gps_altitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='gps_accuracy',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_altitud',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16, null=True),
        ),
    ]
