# Generated by Django 3.2.4 on 2021-07-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_auto_20210718_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='others1_picture',
        ),
        migrations.RemoveField(
            model_name='business',
            name='others2_picture',
        ),
    ]
