# Generated by Django 3.2.4 on 2021-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0048_auto_20210718_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
