# Generated by Django 3.2.4 on 2021-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0051_auto_20210803_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
