# Generated by Django 3.2.4 on 2021-08-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0054_alter_notification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='qrcode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_qrcode', to='business.qrcode'),
        ),
    ]
