# Generated by Django 3.2.4 on 2021-08-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0055_business_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='annual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
