# Generated by Django 3.2.4 on 2021-08-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0057_auto_20210816_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
