# Generated by Django 3.2.4 on 2021-08-26 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0058_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location_rental_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='businessperiod',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collector_business_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_business_periods', to=settings.AUTH_USER_MODEL),
        ),
    ]
