# Generated by Django 3.2.4 on 2021-08-12 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_date', models.DateField(blank=True, null=True)),
                ('semi_annual_date1', models.DateField(blank=True, null=True)),
                ('semi_annual_date2', models.DateField(blank=True, null=True)),
                ('quarter_date1', models.DateField(blank=True, null=True)),
                ('quarter_date2', models.DateField(blank=True, null=True)),
                ('quarter_date3', models.DateField(blank=True, null=True)),
                ('quarter_date4', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedule_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
